apiVersion: v1
kind: ConfigMap
metadata:
  name: circleguard-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  NEO4J_HOST: "neo4j-service"
  NEO4J_PORT: "7687"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  LDAP_HOST: "openldap-service"
  LDAP_PORT: "389"
  LDAP_BASE: "dc=circleguard,dc=edu"
  MAIL_HOST: "mail-service"
  MAIL_PORT: "25"
  AUTH_API_URL: "http://circleguard-auth-service:8180"
  JWT_EXPIRATION: "3600000"
  QR_EXPIRATION: "300"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "50"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "20000"
  SPRING_KAFKA_PRODUCER_PROPERTIES_DELIVERY_TIMEOUT_MS: "30000"
  SPRING_KAFKA_PRODUCER_PROPERTIES_REQUEST_TIMEOUT_MS: "10000"
  SPRING_KAFKA_PRODUCER_PROPERTIES_LINGER_MS: "20"
  SPRING_KAFKA_PRODUCER_BATCH_SIZE: "16384"
