spring:
  application:
    name: circleguard-gateway-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:my-super-secret-dev-key-32-chars-long-12345678}
  expiration: ${JWT_EXPIRATION:3600000}

qr:
  secret: ${QR_SECRET:my-qr-secret-key-for-dev-1234567890}
  expiration: ${QR_EXPIRATION:300}

server:
  port: ${SERVER_PORT:8087}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
