apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-file-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: circleguard-file-service
  template:
    metadata:
      labels:
        app: circleguard-file-service
    spec:
      serviceAccountName: circleguard-service
      containers:
      - name: file-service
        image: circleguard-file-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: circleguard-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-file-service
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: circleguard-file-service
