apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-gateway-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: circleguard-gateway-service
  template:
    metadata:
      labels:
        app: circleguard-gateway-service
    spec:
      serviceAccountName: circleguard-service
      containers:
      - name: gateway-service
        image: circleguard-gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: circleguard-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-jwt-secret
              key: JWT_SECRET
        - name: QR_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-qr-secret
              key: QR_SECRET
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8087
          initialDelaySeconds: 25
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8087
          initialDelaySeconds: 50
          periodSeconds: 20
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8087
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 24
        resources:
          requests:
            cpu: 200m
            memory: 192Mi
          limits:
            cpu: 500m
            memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-gateway-service
spec:
  ports:
  - port: 8087
    targetPort: 8087
  selector:
    app: circleguard-gateway-service
