apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-identity-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: circleguard-identity-service
  template:
    metadata:
      labels:
        app: circleguard-identity-service
    spec:
      containers:
      - name: identity-service
        image: circleguard-identity-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: circleguard-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: DB_NAME
          value: circleguard_identity
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: circleguard-db-credentials
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: circleguard-db-credentials
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-jwt-secret
              key: JWT_SECRET
        - name: VAULT_SECRET
          valueFrom:
            secretKeyRef:
              name: circleguard-vault-secret
              key: VAULT_SECRET
        - name: VAULT_SALT
          valueFrom:
            secretKeyRef:
              name: circleguard-vault-secret
              key: VAULT_SALT
        - name: VAULT_HASH_SALT
          valueFrom:
            secretKeyRef:
              name: circleguard-vault-secret
              key: VAULT_HASH_SALT
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-identity-service
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: circleguard-identity-service
