input {
  beats {
    port => 5044
  }

  http {
    port => 8081
    codec => json
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "circleguard" }
    }
  }

  if ![environment] {
    mutate {
      add_field => { "environment" => "dev" }
    }
  }

  mutate {
    lowercase => [ "service", "environment" ]
  }
}

output {
  elasticsearch {
    hosts => [ "http://elasticsearch:9200" ]
    index => "circleguard-%{[service]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
