global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "circleguard-monitor"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: demo-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["demo-app:8080"]
    labels:
      application: demo-app
      environment: dev

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8180"]
    labels:
      application: auth-service
      environment: dev

  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8087"]
    labels:
      application: gateway-service
      environment: dev
