apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-finops-scaler
  namespace: circleguard-dev
  labels:
    app.kubernetes.io/part-of: circleguard
    circleguard.io/bonus: finops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: circleguard-finops-scaler
  namespace: circleguard-dev
  labels:
    app.kubernetes.io/part-of: circleguard
    circleguard.io/bonus: finops
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: circleguard-finops-scaler
  namespace: circleguard-dev
  labels:
    app.kubernetes.io/part-of: circleguard
    circleguard.io/bonus: finops
subjects:
  - kind: ServiceAccount
    name: circleguard-finops-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: circleguard-finops-scaler
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: circleguard-scale-noncritical-down
  namespace: circleguard-dev
  labels:
    app.kubernetes.io/part-of: circleguard
    circleguard.io/bonus: finops
spec:
  schedule: "0 21 * * 1-5"
  timeZone: America/Bogota
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: circleguard-finops-scaler
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:1.34
              command:
                - /bin/sh
                - -c
                - >
                  kubectl -n circleguard-dev scale deployment/circleguard-dashboard-service --replicas=0 &&
                  kubectl -n circleguard-dev scale deployment/circleguard-file-service --replicas=0
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: circleguard-scale-noncritical-up
  namespace: circleguard-dev
  labels:
    app.kubernetes.io/part-of: circleguard
    circleguard.io/bonus: finops
spec:
  schedule: "0 6 * * 1-5"
  timeZone: America/Bogota
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: circleguard-finops-scaler
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:1.34
              command:
                - /bin/sh
                - -c
                - >
                  kubectl -n circleguard-dev scale deployment/circleguard-dashboard-service --replicas=1 &&
                  kubectl -n circleguard-dev scale deployment/circleguard-file-service --replicas=1
