package com.circleguard.promotion.service;

import com.circleguard.promotion.model.graph.CircleNode;
import com.circleguard.promotion.repository.graph.CircleNodeRepository;
import com.circleguard.promotion.repository.graph.UserNodeRepository;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class AutoCircleServiceUnitTest {

    @Test
    void shouldIgnoreInvalidOrShortEncounters() {
        UserNodeRepository userRepository = mock(UserNodeRepository.class);
        CircleNodeRepository circleRepository = mock(CircleNodeRepository.class);
        CircleService circleService = mock(CircleService.class);
        AutoCircleService service = new AutoCircleService(userRepository, circleRepository, circleService);
        when(userRepository.getCumulativeEncounterDuration("u1", "u2")).thenReturn(120L);

        service.evaluateEncounter(null, "u2");
        service.evaluateEncounter("u1", "u1");
        service.evaluateEncounter("u1", "u2");

        verify(circleRepository, never()).save(any());
    }

    @Test
    void shouldCreateAutoCircleForLongUnconnectedEncounter() {
        UserNodeRepository userRepository = mock(UserNodeRepository.class);
        CircleNodeRepository circleRepository = mock(CircleNodeRepository.class);
        CircleService circleService = mock(CircleService.class);
        when(userRepository.getCumulativeEncounterDuration("u1", "u2")).thenReturn(3600L);
        when(circleRepository.findCommonCircles("u1", "u2")).thenReturn(List.of());

        new AutoCircleService(userRepository, circleRepository, circleService).evaluateEncounter("u1", "u2");

        verify(circleRepository).save(any(CircleNode.class));
        verify(circleService).joinCircle(org.mockito.ArgumentMatchers.eq("u1"), org.mockito.ArgumentMatchers.startsWith("AUTO-"));
        verify(circleService).joinCircle(org.mockito.ArgumentMatchers.eq("u2"), org.mockito.ArgumentMatchers.startsWith("AUTO-"));
    }

    @Test
    void shouldSkipWhenUsersAlreadyShareAutoCircle() {
        UserNodeRepository userRepository = mock(UserNodeRepository.class);
        CircleNodeRepository circleRepository = mock(CircleNodeRepository.class);
        CircleService circleService = mock(CircleService.class);
        when(userRepository.getCumulativeEncounterDuration("u1", "u2")).thenReturn(4000L);
        when(circleRepository.findCommonCircles("u1", "u2"))
                .thenReturn(List.of(CircleNode.builder().isAutoGenerated(true).build()));

        new AutoCircleService(userRepository, circleRepository, circleService).evaluateEncounter("u1", "u2");

        verify(circleRepository, never()).save(any());
        assertTrue(true);
    }
}
