apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Configuration
  - configmaps/circleguard-config.yaml
  - configmaps/postgres-init-config.yaml
  - secrets/circleguard-secrets.yaml
  # RBAC
  - rbac/services-rbac.yaml
  # Middleware
  - postgres/postgres.yaml
  - neo4j/neo4j.yaml
  - redis/redis.yaml
  - kafka/zookeeper.yaml
  - kafka/kafka.yaml
  - openldap/openldap.yaml
  # Microservices
  - services/identity-service.yaml
  - services/auth-service.yaml
  - services/form-service.yaml
  - services/promotion-service.yaml
  - services/gateway-service.yaml
  - services/notification-service.yaml
  - services/dashboard-service.yaml
  - services/file-service.yaml
  # TLS (requires cert-manager installed in cluster)
  - cert-manager/cluster-issuer.yaml
  - cert-manager/gateway-certificate.yaml
