apiVersion: v1
kind: Secret
metadata:
  name: circleguard-db-credentials
type: Opaque
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-neo4j-credentials
type: Opaque
stringData:
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-ldap-credentials
type: Opaque
stringData:
  LDAP_USER: cn=admin,dc=circleguard,dc=edu
  LDAP_PASSWORD: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-jwt-secret
type: Opaque
stringData:
  JWT_SECRET: my-super-secret-dev-key-32-chars-long-12345678
---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-qr-secret
type: Opaque
stringData:
  QR_SECRET: my-qr-secret-key-for-dev-1234567890
---
apiVersion: v1
kind: Secret
metadata:
  name: circleguard-vault-secret
type: Opaque
stringData:
  VAULT_SECRET: 746573742d7365637265742d33322d63686172732d6c6f6e672d313233343536
  VAULT_SALT: deadbeef
  VAULT_HASH_SALT: "12345678"
