spring:
  application:
    name: circleguard-notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

auth:
  api:
    url: ${AUTH_API_URL:http://localhost:8180}

jwt:
  secret: "${JWT_SECRET:my-super-secret-dev-key-32-chars-long-12345678}"
  expiration: ${JWT_EXPIRATION:3600000}

qr:
  secret: "${QR_SECRET:my-qr-secret-key-for-dev-1234567890}"
  expiration: ${QR_EXPIRATION:300}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
